logo: showlab.png|width=50% height=50%
title: AssistQ
description: Affordance-centric Question-driven Task Completion for Egocentric Assistant
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
theme: jekyll-theme-minimal
